#!/usr/bin/env python3
"""Strip Format/archive tracking junk from static front HTML without breaking sliders."""

from __future__ import annotations

import re
from pathlib import Path

from bs4 import BeautifulSoup, Comment

FRONT = Path("/root/sheyanova/front")

# CSS never needed for portfolio viewing
REMOVE_CSS_SUBSTR = (
    "/sales/cart-",
    "/client_access/",
    "blog_defaults-",
    "/blog-",
    "share_panel-",
    "theme_social-",
)

# Script src patterns to drop always
REMOVE_SCRIPT_SRC_SUBSTR = (
    "4ormat-70901225320ae427277039851b0e0b51e410c74562a86d842c56870b6226e02e",  # wayback-contaminated
    "content_page-",
    "custom_pages-",
    "jquery.fitvid",
    "reframe.min",
    "ls.parent-fit",
)

# Keep comparison stack only when page has comparison sliders
COMPARISON_ONLY_SRC_SUBSTR = (
    "comparison-slider.bundle",
    "4ormat-90922ef41128d245f68c9e8b2a3902b95fa9a9a1409f6c96f7e7e636fd7e803d",
)

# Meta names/attrs that are Format workflow leftovers
REMOVE_META = {
    "protect_images",
    "image_protection_blurb",
    "current_path",
}

SKIP_DIR_PARTS = ("/web/", "/web.archive.org/", "/https:")


def is_front_page(path: Path) -> bool:
    s = str(path)
    return path.suffix == ".html" and not any(p in s for p in SKIP_DIR_PARTS)


def script_text(tag) -> str:
    return tag.string or tag.get_text() or ""


def is_nreum_script(tag) -> bool:
    src = (tag.get("src") or "").lower()
    if "nr-loader" in src or "newrelic" in src:
        return True
    t = script_text(tag)
    return "NREUM" in t or "newrelic" in t.lower()


def is_analytics_inline(tag) -> bool:
    if tag.get("src"):
        return False
    t = script_text(tag).strip()
    if not t:
        return False
    # Empty GA stub
    if re.fullmatch(r"var\s+_gaq\s*=\s*_gaq\s*\|\|\s*\[\];", t, re.S):
        return True
    # Format ClickStack / random beacon
    if "XMLHttpRequest" in t and ("format.com" in t or "ClickStack" in t or "Math.floor(Math.random()" in t):
        return True
    # Format mobile preview banner (G024)
    if "getUrlVars" in t and ("G024_info" in t or "Your website preview" in t):
        return True
    # Wayback remnants
    if "__WB_pmw" in t or "_____WB$wombat" in t or "archive.org" in t:
        return True
    return False


def is_junk_comment(text: str) -> bool:
    t = text.strip().lower()
    if not t:
        return True
    markers = (
        "note: this is what is generated by the theme",
        "4ormat",
        "format.com",
        "begin wayback",
        "end wayback",
        "file archived",
    )
    return any(m in t for m in markers)


def should_remove_link(href: str) -> bool:
    if not href:
        return False
    h = href.lower()
    if any(s in h for s in REMOVE_CSS_SUBSTR):
        return True
    # wget leftover local google-fonts stub
    if h.startswith("css2?") or "css2?family=" in h and not h.startswith("http"):
        return True
    return False


def should_remove_script_src(src: str, has_comparison: bool) -> bool:
    if not src:
        return False
    if any(s in src for s in REMOVE_SCRIPT_SRC_SUBSTR):
        return True
    if not has_comparison and any(s in src for s in COMPARISON_ONLY_SRC_SUBSTR):
        return True
    return False


def clean_html(path: Path) -> dict:
    raw = path.read_text(encoding="utf-8", errors="replace")
    before = len(raw)
    soup = BeautifulSoup(raw, "html.parser")
    has_comparison = bool(soup.select(".comparison_slider, .format_comparison_slider"))
    stats = {
        "path": str(path.relative_to(FRONT)),
        "nreum": 0,
        "analytics": 0,
        "links": 0,
        "scripts": 0,
        "meta": 0,
        "comments": 0,
        "has_comparison": has_comparison,
        "bytes_before": before,
    }

    for tag in list(soup.find_all("script")):
        if is_nreum_script(tag):
            tag.decompose()
            stats["nreum"] += 1
            continue
        if is_analytics_inline(tag):
            tag.decompose()
            stats["analytics"] += 1
            continue
        src = tag.get("src") or ""
        if should_remove_script_src(src, has_comparison):
            tag.decompose()
            stats["scripts"] += 1

    for tag in list(soup.find_all("link")):
        href = tag.get("href") or ""
        if should_remove_link(href):
            tag.decompose()
            stats["links"] += 1

    for tag in list(soup.find_all("meta")):
        name = (tag.get("name") or "").lower()
        if name in REMOVE_META:
            tag.decompose()
            stats["meta"] += 1
            continue
        # turbolinks track stub
        if tag.has_attr("data-turbolinks-track") or tag.get("src") == "version-1752860274":
            tag.decompose()
            stats["meta"] += 1

    for c in list(soup.find_all(string=lambda x: isinstance(x, Comment))):
        if is_junk_comment(str(c)):
            c.extract()
            stats["comments"] += 1

    # Drop foo="bar" junk attrs on links
    for tag in soup.find_all(True):
        if tag.has_attr("foo"):
            del tag["foo"]

    out = str(soup)
    # BeautifulSoup may inject <html><body> around fragments; our pages are full docs
    path.write_text(out, encoding="utf-8")
    stats["bytes_after"] = len(out)
    return stats


def main() -> None:
    pages = sorted(p for p in FRONT.rglob("*.html") if is_front_page(p))
    print(f"Cleaning {len(pages)} HTML files…")
    totals = {"nreum": 0, "analytics": 0, "links": 0, "scripts": 0, "meta": 0, "comments": 0}
    for p in pages:
        s = clean_html(p)
        for k in totals:
            totals[k] += s[k]
        saved = s["bytes_before"] - s["bytes_after"]
        print(
            f"  {s['path']}: -{saved}B nreum={s['nreum']} analytics={s['analytics']} "
            f"links={s['links']} scripts={s['scripts']} meta={s['meta']} cmp={s['has_comparison']}"
        )
    print("TOTALS", totals)


if __name__ == "__main__":
    main()
